package de.flxw.admintools.utils;

import de.flxw.admintools.mysql.MySQL;
import org.bukkit.ChatColor;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;

public class FileManager {

    public static File getConfigFile() {return new File("plugins/AdminTools v3", "config.yml");}
    public static FileConfiguration getConfigFileConfiguration() {return YamlConfiguration.loadConfiguration(getConfigFile());}
    public static File getMySQL() {return new File("plugins/AdminTools v3", "mysql.yml");}
    public static FileConfiguration getMySQLConfig() {return YamlConfiguration.loadConfiguration(getMySQL());}

    public static void setStandardConfig()
    {
        if(!getConfigFile().exists())
        {
            new FileCopy().copy(AdminTools.getInstance().getResource("config.yml"), getConfigFile());
        }
    }
    public static void readConfig()
    {
        FileConfiguration cfg = getConfigFileConfiguration();

        String prefix = cfg.getString("Prefixes.mainPrefix");
        String muteprefix = cfg.getString("Prefixes.mutePrefix");
        String banprefix = cfg.getString("Prefixes.banPrefix");
        String noperm = cfg.getString("ServerMessages.nopermission");
        String noplayer = cfg.getString("ServerMessages.noplayer");
        String playernull = cfg.getString("ServerMessages.playerNotOnline");
        String joinMessage = cfg.getString("ServerMessages.joinMessageNormal");
        String joinMessageTeam = cfg.getString("ServerMessages.joinMessageTeam");
        String quitMessage = cfg.getString("ServerMessages.quitMessage");
        String broadcastPrefix = cfg.getString("ChatMessages.broadcastPrefix");
        String broadcastWarning = cfg.getString("ChatMessages.broadcastColorcodesWarning");
        String msgPrefix = cfg.getString("Prefixes.msgPrefix");
        String spyPrefix = cfg.getString("Prefixes.socialspyPrefix");
        String ping = cfg.getString("ChatMessages.pingMessage");
        String bypass = cfg.getString("ChatMessages.bypassMessage");
        String nlbypass = cfg.getString("ChatMessages.noLongerBypassMessage");
        String censorMessage = cfg.getString("ChatMessages.censorMessage");
        String nocensorMessage = cfg.getString("ChatMessages.noLongerCensorMessage");
        String othercensorMessage = cfg.getString("ChatMessages.otherCensorMessage");
        String othernolongercensor = cfg.getString("ChatMessages.otherNoLongerCensorMessage");
        String chatclear = cfg.getString("ChatMessages.clearChatMessage");
        String isbypassing = cfg.getString("ChatMessages.isBypassingMessage");
        String enderchest = cfg.getString("ChatMessages.enderchestOpenMessage");
        String otherenderchest = cfg.getString("ChatMessages.otherEnderchestOpenMessage");
        String feedmessage = cfg.getString("ChatMessages.feedMessage");
        String otherfeedmessage = cfg.getString("ChatMessages.otherFeedMessage");
        String allfeed = cfg.getString("ChatMessages.allPlayerFeedMessage");
        String flymessage = cfg.getString("ChatMessages.flyMessage");
        String otherflymessage = cfg.getString("ChatMessages.flyOtherMessage");
        String nolongerfly = cfg.getString("ChatMessages.noLongerFlyMessage");
        String gamemode = cfg.getString("ChatMessages.gamemodeMessage");
        String othergamemode = cfg.getString("ChatMessages.otherGamemodeMessage");
        String othernolongerfly = cfg.getString("ChatMessages.noLongerFlyOtherMessage");
        String freeze = cfg.getString("ChatMessages.freezeMessage");
        String nofreeze = cfg.getString("ChatMessages.noLongerFreezeMessage");
        String otherfreeze = cfg.getString("ChatMessages.otherFreezeMessage");
        String othernofreeze = cfg.getString("ChatMessages.otherNoLongerFreezeMessage");
        String kickHeader = cfg.getString("KickConfig.kickHeader");
        String kickReason = cfg.getString("KickConfig.kickReason");
        String kickedBy = cfg.getString("KickConfig.kickedBy");
        String banHeader = cfg.getString("BanConfig.banHeader");
        String banReason = cfg.getString("BanConfig.banReason");
        String bannedBy = cfg.getString("BanConfig.bannedBy");
        String banRemaining = cfg.getString("BanConfig.remainingBanTime");
        String banAppeal = cfg.getString("BanConfig.banAppeal");
        String alreadyBanned = cfg.getString("BanConfig.alreadyBanned");
        String banned = cfg.getString("BanConfig.banned");
        String muteMessage = cfg.getString("MuteMessages.mute");
        String disallowMessage = cfg.getString("MuteMessages.disallowMessage");
        String giveawayCount = cfg.getString("GiveawayConfig.giveawayCountdown");
        String givewayWinMessage = cfg.getString("GiveawayConfig.giveawayWinnerMessage");
        String freezeTitle1 = cfg.getString("FreezeConfig.freezeTitle1");
        String freezeTitle2 = cfg.getString("FreezeConfig.freezeTitle2");
        String giveawaynot = cfg.getString("GiveawayConfig.giveawayNotEnoughPlayers");
        String giveawaystart = cfg.getString("GiveawayConfig.giveawayStarted");
        String godmode = cfg.getString("ChatMessages.godmodeMessage");
        String noLongerGodmode = cfg.getString("ChatMessages.noLongerGodmodeMessage");
        String othergodmode = cfg.getString("ChatMessages.otherGodmodeMessage");
        String noLongerOthergodmode = cfg.getString("ChatMessages.noLongerOtherGodmodeMessage");
        String heal = cfg.getString("ChatMessages.healMessage");
        String otherheal = cfg.getString("ChatMessages.otherHealMessage");
        String allheal = cfg.getString("ChatMessages.allPlayerHealMessage");
        String allkicked = cfg.getString("KickConfig.allKickedMessage");
        String lockchat = cfg.getString("ChatMessages.lockchatMessage");
        String unlockchat = cfg.getString("ChatMessages.unlockchatMessage");
        String lockchatdeny = cfg.getString("ChatMessages.lockchatDenyMessage");
        String alreadyMuted = cfg.getString("MuteMessages.alreadyMuted");
        String staffMute = cfg.getString("MuteMessages.staffMessage");
        String rename = cfg.getString("ChatMessages.renameMessage");
        String renamevalid = cfg.getString("ChatMessages.renameValidItem");
        String renamecolorwarning = cfg.getString("ChatMessages.renameColorcodesWarning");
        String sign = cfg.getString("ChatMessages.signMessage");
        String signvalid = cfg.getString("ChatMessages.signInvalidItem");
        String signcolorwarning = cfg.getString("ChatMessages.signColorcodesWarning");
        String skullname = cfg.getString("Settings.SkullName");
        String skullmessage = cfg.getString("ChatMessages.skullMessage");
        String otherskullmessage = cfg.getString("ChatMessages.otherSkullMessage");
        String socialspy = cfg.getString("ChatMessages.socialspyEnableMessage");
        String disablesocialspy = cfg.getString("ChatMessages.socialspyDisableMessage");
        String othersocialspy = cfg.getString("ChatMessages.otherSocialspyEnableMessage");
        String otherdisablesocialspy = cfg.getString("ChatMessages.otherSocialspyDisableMessage");
        String speed = cfg.getString("ChatMessages.speedMessage");
        String otherspeed = cfg.getString("ChatMessages.otherSpeedMessage");
        String speedvalid = cfg.getString("ChatMessages.speedInvalidMessage");
        String time = cfg.getString("ChatMessages.personalTimeMessage");
        String tpaincomming = cfg.getString("ChatMessages.tpaIncommingMessage");
        String tpasender = cfg.getString("ChatMessages.tpaSenderMessage");
        String tpall = cfg.getString("ChatMessages.tpallMessage");
        String othertpall = cfg.getString("ChatMessages.otherTpallMessage");
        String tpdeny = cfg.getString("ChatMessages.tpdenyMessage");
        String othertpdeny = cfg.getString("ChatMessages.otherTpdenyMessage");
        String tpaccept = cfg.getString("ChatMessages.tpacceptMessage");
        String othertpaccept = cfg.getString("ChatMessages.otherTpacceptMessage");
        String tphere = cfg.getString("ChatMessages.tphereMessage");
        String othertphere = cfg.getString("ChatMessages.otherTphereMessage");
        String unban = cfg.getString("BanConfig.unbanMessage");
        String isnotbanned = cfg.getString("BanConfig.isNotBannedMessage");
        String isnotmuted = cfg.getString("MuteMessages.isNotMuted");
        String unmute = cfg.getString("MuteMessages.unmuteMessage");
        String vanish = cfg.getString("ChatMessages.vanishMessage");
        String novanish = cfg.getString("ChatMessages.noLongerVanishMessage");
        String othervanish = cfg.getString("ChatMessages.otherVanishMessage");
        String othernovanish = cfg.getString("ChatMessages.otherNoLongerVanishMessage");
        String weather = cfg.getString("ChatMessages.personalWeatherMessage");
        String workbench = cfg.getString("ChatMessages.workbenchMessage");
        String otherworkbench = cfg.getString("ChatMessages.otherWorkbenchMessage");
        String adminchatlogin = cfg.getString("ChatMessages.adminchatLogInMessage");
        String adminchatlogoff = cfg.getString("ChatMessages.adminchatLogOffMessage");
        String adminchatalreadylogon = cfg.getString("ChatMessages.adminchatAlreadyLogInMessage");
        String hatCommandMessage = cfg.getString("ChatMessages.hatCommandMessage");
        String noLongerHatCommandMessage = cfg.getString("ChatMessages.noLongerHatCommandMessage");
        String otherHatCommandMessage = cfg.getString("ChatMessages.otherHatCommandMessage");
        String otherNoLongerHatCommandMessage = cfg.getString("ChatMessages.otherNoLongerHatCommandMessage");
        String errorHatMessage = cfg.getString("ChatMessages.errorHatMessage");
        String adminchatalreadylogoff = cfg.getString("ChatMessages.adminchatAlreadyLogOffMessage");
        String antiban = cfg.getString("BanConfig.cannotBanMessage");
        String antimute = cfg.getString("MuteMessages.cannotMuteMessage");
        String modtline1 = cfg.getString("Settings.modtLine1");
        String modtline2 = cfg.getString("Settings.modtLine2");
        String unknowncommand = cfg.getString("Settings.unknownCommandMessage");
        String publictime = cfg.getString("ChatMessages.timeMessage");
        String msgerror = cfg.getString("ChatMessages.msgReplyToYourselfMessage");
        String adminchat = cfg.getString("ChatMessages.adminchatRespondMessage");
        String toggleMsgMessage = ChatColor.translateAlternateColorCodes('&', cfg.getString("ChatMessages.toggleMsgMessage"));
        String otherToggleMsgMessage = ChatColor.translateAlternateColorCodes('&', cfg.getString("ChatMessages.otherToggleMsgMessage"));
        String noMsgMessage = ChatColor.translateAlternateColorCodes('&', cfg.getString("ChatMessages.noMsgMessage"));
        prefix = ChatColor.translateAlternateColorCodes('&', prefix);
        banprefix = ChatColor.translateAlternateColorCodes('&', banprefix);
        muteprefix = ChatColor.translateAlternateColorCodes('&', muteprefix);
        noperm = ChatColor.translateAlternateColorCodes('&', noperm);
        noplayer = ChatColor.translateAlternateColorCodes('&', noplayer);
        playernull = ChatColor.translateAlternateColorCodes('&', playernull);
        joinMessage = ChatColor.translateAlternateColorCodes('&', joinMessage);
        joinMessageTeam = ChatColor.translateAlternateColorCodes('&', joinMessageTeam);
        quitMessage = ChatColor.translateAlternateColorCodes('&', quitMessage);
        broadcastPrefix = ChatColor.translateAlternateColorCodes('&', broadcastPrefix);
        bypass = ChatColor.translateAlternateColorCodes('&', bypass);
        isbypassing = ChatColor.translateAlternateColorCodes('&', isbypassing);
        nlbypass = ChatColor.translateAlternateColorCodes('&', nlbypass);
        broadcastWarning = ChatColor.translateAlternateColorCodes('&', broadcastWarning);
        censorMessage = ChatColor.translateAlternateColorCodes('&', censorMessage);
        feedmessage = ChatColor.translateAlternateColorCodes('&', feedmessage);
        otherfeedmessage = ChatColor.translateAlternateColorCodes('&', otherfeedmessage);
        allfeed = ChatColor.translateAlternateColorCodes('&', allfeed);
        enderchest = ChatColor.translateAlternateColorCodes('&', enderchest);
        otherenderchest = ChatColor.translateAlternateColorCodes('&', otherenderchest);
        nocensorMessage = ChatColor.translateAlternateColorCodes('&', nocensorMessage);
        chatclear = ChatColor.translateAlternateColorCodes('&', chatclear);
        othercensorMessage = ChatColor.translateAlternateColorCodes('&', othercensorMessage);
        othernolongercensor = ChatColor.translateAlternateColorCodes('&', othernolongercensor);
        flymessage = ChatColor.translateAlternateColorCodes('&', flymessage);
        otherflymessage = ChatColor.translateAlternateColorCodes('&', otherflymessage);
        nolongerfly = ChatColor.translateAlternateColorCodes('&', nolongerfly);
        othernolongerfly = ChatColor.translateAlternateColorCodes('&', othernolongerfly);
        freeze = ChatColor.translateAlternateColorCodes('&', freeze);
        nofreeze = ChatColor.translateAlternateColorCodes('&', nofreeze);
        otherfreeze = ChatColor.translateAlternateColorCodes('&', otherfreeze);
        othernofreeze = ChatColor.translateAlternateColorCodes('&', othernofreeze);
        gamemode = ChatColor.translateAlternateColorCodes('&', gamemode);
        othergamemode = ChatColor.translateAlternateColorCodes('&', othergamemode);
        msgPrefix = ChatColor.translateAlternateColorCodes('&', msgPrefix);
        spyPrefix = ChatColor.translateAlternateColorCodes('&', spyPrefix);
        kickHeader = ChatColor.translateAlternateColorCodes('&', kickHeader);
        kickReason = ChatColor.translateAlternateColorCodes('&', kickReason);
        kickedBy = ChatColor.translateAlternateColorCodes('&', kickedBy);
        banHeader = ChatColor.translateAlternateColorCodes('&', banHeader);
        banReason = ChatColor.translateAlternateColorCodes('&', banReason);
        bannedBy = ChatColor.translateAlternateColorCodes('&', bannedBy);
        banRemaining = ChatColor.translateAlternateColorCodes('&', banRemaining);
        banAppeal = ChatColor.translateAlternateColorCodes('&', banAppeal);
        muteMessage = ChatColor.translateAlternateColorCodes('&', muteMessage);
        disallowMessage = ChatColor.translateAlternateColorCodes('&', disallowMessage);
        giveawayCount = ChatColor.translateAlternateColorCodes('&', giveawayCount);
        givewayWinMessage = ChatColor.translateAlternateColorCodes('&', givewayWinMessage);
        freezeTitle1 = ChatColor.translateAlternateColorCodes('&', freezeTitle1);
        freezeTitle2 = ChatColor.translateAlternateColorCodes('&', freezeTitle2);
        ping = ChatColor.translateAlternateColorCodes('&', ping);
        alreadyBanned = ChatColor.translateAlternateColorCodes('&', alreadyBanned);
        banned = ChatColor.translateAlternateColorCodes('&', banned);
        giveawaynot = ChatColor.translateAlternateColorCodes('&', giveawaynot);
        giveawaystart = ChatColor.translateAlternateColorCodes('&', giveawaystart);
        godmode = ChatColor.translateAlternateColorCodes('&', godmode);
        othergodmode = ChatColor.translateAlternateColorCodes('&', othergodmode);
        noLongerGodmode = ChatColor.translateAlternateColorCodes('&', noLongerGodmode);
        noLongerOthergodmode = ChatColor.translateAlternateColorCodes('&', noLongerOthergodmode);
        heal = ChatColor.translateAlternateColorCodes('&', heal);
        otherheal = ChatColor.translateAlternateColorCodes('&', otherheal);
        allheal = ChatColor.translateAlternateColorCodes('&', allheal);
        allkicked = ChatColor.translateAlternateColorCodes('&', allkicked);
        unlockchat = ChatColor.translateAlternateColorCodes('&', unlockchat);
        lockchat = ChatColor.translateAlternateColorCodes('&', lockchat);
        lockchatdeny = ChatColor.translateAlternateColorCodes('&', lockchatdeny);
        alreadyMuted = ChatColor.translateAlternateColorCodes('&', alreadyMuted);
        staffMute = ChatColor.translateAlternateColorCodes('&', staffMute);
        rename = ChatColor.translateAlternateColorCodes('&', rename);
        renamevalid = ChatColor.translateAlternateColorCodes('&', renamevalid);
        renamecolorwarning = ChatColor.translateAlternateColorCodes('&', renamecolorwarning);
        sign = ChatColor.translateAlternateColorCodes('&', sign);
        signvalid = ChatColor.translateAlternateColorCodes('&', signvalid);
        signcolorwarning = ChatColor.translateAlternateColorCodes('&', signcolorwarning);
        skullname = ChatColor.translateAlternateColorCodes('&', skullname);
        skullmessage = ChatColor.translateAlternateColorCodes('&', skullmessage);
        otherskullmessage = ChatColor.translateAlternateColorCodes('&', otherskullmessage);
        socialspy = ChatColor.translateAlternateColorCodes('&', socialspy);
        disablesocialspy = ChatColor.translateAlternateColorCodes('&', disablesocialspy);
        othersocialspy = ChatColor.translateAlternateColorCodes('&', othersocialspy);
        otherdisablesocialspy = ChatColor.translateAlternateColorCodes('&', otherdisablesocialspy);
        speed = ChatColor.translateAlternateColorCodes('&', speed);
        otherspeed = ChatColor.translateAlternateColorCodes('&', otherspeed);
        speedvalid = ChatColor.translateAlternateColorCodes('&', speedvalid);
        time = ChatColor.translateAlternateColorCodes('&', time);
        tpaincomming = ChatColor.translateAlternateColorCodes('&', tpaincomming);
        tpasender = ChatColor.translateAlternateColorCodes('&', tpasender);
        tpall = ChatColor.translateAlternateColorCodes('&', tpall);
        othertpall = ChatColor.translateAlternateColorCodes('&', othertpall);
        tpdeny = ChatColor.translateAlternateColorCodes('&', tpdeny);
        othertpdeny = ChatColor.translateAlternateColorCodes('&', othertpdeny);
        tpaccept = ChatColor.translateAlternateColorCodes('&', tpaccept);
        othertpaccept = ChatColor.translateAlternateColorCodes('&', othertpaccept);
        tphere = ChatColor.translateAlternateColorCodes('&', tphere);
        othertphere = ChatColor.translateAlternateColorCodes('&', othertphere);
        unban = ChatColor.translateAlternateColorCodes('&', unban);
        isnotbanned = ChatColor.translateAlternateColorCodes('&', isnotbanned);
        unmute = ChatColor.translateAlternateColorCodes('&', unmute);
        isnotmuted = ChatColor.translateAlternateColorCodes('&', isnotmuted);
        vanish = ChatColor.translateAlternateColorCodes('&', vanish);
        novanish = ChatColor.translateAlternateColorCodes('&', novanish);
        othervanish = ChatColor.translateAlternateColorCodes('&', othervanish);
        othernovanish = ChatColor.translateAlternateColorCodes('&', othernovanish);
        weather = ChatColor.translateAlternateColorCodes('&', weather);
        workbench = ChatColor.translateAlternateColorCodes('&', workbench);
        otherworkbench = ChatColor.translateAlternateColorCodes('&', otherworkbench);
        antiban = ChatColor.translateAlternateColorCodes('&', antiban);
        antimute = ChatColor.translateAlternateColorCodes('&', antimute);
        publictime = ChatColor.translateAlternateColorCodes('&', publictime);
        msgerror = ChatColor.translateAlternateColorCodes('&', msgerror);
        adminchat = ChatColor.translateAlternateColorCodes('&', adminchat);
        adminchatlogin = ChatColor.translateAlternateColorCodes('&', adminchatlogin);
        adminchatlogoff = ChatColor.translateAlternateColorCodes('&', adminchatlogoff);
        adminchatalreadylogoff = ChatColor.translateAlternateColorCodes('&', adminchatalreadylogoff);
        errorHatMessage = ChatColor.translateAlternateColorCodes('&', errorHatMessage);
        otherNoLongerHatCommandMessage = ChatColor.translateAlternateColorCodes('&', otherNoLongerHatCommandMessage);
        otherHatCommandMessage = ChatColor.translateAlternateColorCodes('&', otherHatCommandMessage);
        noLongerHatCommandMessage = ChatColor.translateAlternateColorCodes('&', noLongerHatCommandMessage);
        hatCommandMessage = ChatColor.translateAlternateColorCodes('&', hatCommandMessage);
        adminchatalreadylogon = ChatColor.translateAlternateColorCodes('&', adminchatalreadylogon);
        boolean modt = cfg.getBoolean("Settings.modt");
        boolean unknown = cfg.getBoolean("Settings.unknownCommand");
        if(modt)
        {
            modtline1 = ChatColor.translateAlternateColorCodes('&', modtline1);
            modtline2 = ChatColor.translateAlternateColorCodes('&', modtline2);
        }
        if(unknown)
        {
            unknowncommand = ChatColor.translateAlternateColorCodes('&', unknowncommand);
        }
        boolean mysql = cfg.getBoolean("mysql");
        boolean denyBuildWhileFreezed = cfg.getBoolean("FreezeConfig.denyBuildWhileFreezed");
        boolean logip = cfg.getBoolean("Settings.logIpAddress");
        boolean updatemessage = cfg.getBoolean("Settings.disableUpdateMessageOnJoin");
        int giveawaycount = cfg.getInt("GiveawayConfig.giveawaySeconds");
        int pingLightgreen = cfg.getInt("Settings.pingLightgreen");
        int pingDarkgreen = cfg.getInt("Settings.pingDarkgreen");
        int pingLightred = cfg.getInt("Settings.pingLightred");
        int maxplayers = cfg.getInt("Settings.maxPlayers");
        AdminTools.getInstance().Prefix = prefix;
        AdminTools.getInstance().BanPrefix = banprefix;
        AdminTools.getInstance().MutePrefix = muteprefix;
        AdminTools.getInstance().NoPerm = noperm;
        AdminTools.getInstance().NoPlayer = noplayer;
        AdminTools.getInstance().PlayerNotOnline = playernull;
        AdminTools.getInstance().JoinMessage = joinMessage;
        AdminTools.getInstance().JoinMessageTeam = joinMessageTeam;
        AdminTools.getInstance().BroadcastPrefix = broadcastPrefix;
        AdminTools.getInstance().BroadcastWarning = broadcastWarning;
        AdminTools.getInstance().MsgPrefix = msgPrefix;
        AdminTools.getInstance().SocialspyPrefix = spyPrefix;
        AdminTools.getInstance().BypassMessage = bypass;
        AdminTools.getInstance().IsBypassingMessage = isbypassing;
        AdminTools.getInstance().NoBypassMessage = nlbypass;
        AdminTools.getInstance().KickHeader = kickHeader;
        AdminTools.getInstance().KickReason = kickReason;
        AdminTools.getInstance().KickedBy = kickedBy;
        AdminTools.getInstance().BanHeader = banHeader;
        AdminTools.getInstance().BanReason = banReason;
        AdminTools.getInstance().BannedBy = bannedBy;
        AdminTools.getInstance().RemainingBan = banRemaining;
        AdminTools.getInstance().BanAppeal = banAppeal;
        AdminTools.getInstance().MuteMessage = muteMessage;
        AdminTools.getInstance().DisallowMessage = disallowMessage;
        AdminTools.getInstance().QuitMessage = quitMessage;
        AdminTools.getInstance().GiveawayCount = giveawayCount;
        AdminTools.getInstance().GiveawayWinMessage = givewayWinMessage;
        AdminTools.getInstance().FreezeTitle1 = freezeTitle1;
        AdminTools.getInstance().FreezeTitle2 = freezeTitle2;
        AdminTools.getInstance().DenyBuildWhileFreezed = denyBuildWhileFreezed;
        AdminTools.getInstance().PingMessage = ping;
        AdminTools.getInstance().AlreadyBanned = alreadyBanned;
        AdminTools.getInstance().CensorMessage = censorMessage;
        AdminTools.getInstance().NoCensorMessage = nocensorMessage;
        AdminTools.getInstance().ClearChatMessage = chatclear;
        AdminTools.getInstance().OtherCensorMessage = othercensorMessage;
        AdminTools.getInstance().NoOtherCensorMessage = othernolongercensor;
        AdminTools.getInstance().EnderchestMessage = enderchest;
        AdminTools.getInstance().OtherEnderchestMessage = otherenderchest;
        AdminTools.getInstance().FeedMessage = feedmessage;
        AdminTools.getInstance().OtherFeedMessage = otherfeedmessage;
        AdminTools.getInstance().FlyMessage = flymessage;
        AdminTools.getInstance().OtherFlyMessage = otherflymessage;
        AdminTools.getInstance().NoFlyMessage = nolongerfly;
        AdminTools.getInstance().OtherNoFlyMessage = othernolongerfly;
        AdminTools.getInstance().FreezeMessage = freeze;
        AdminTools.getInstance().NoFreezeMessage = nofreeze;
        AdminTools.getInstance().OtherNoFreezeMessage = othernofreeze;
        AdminTools.getInstance().OtherFreezeMessage = otherfreeze;
        AdminTools.getInstance().GamemodeMessage = gamemode;
        AdminTools.getInstance().OtherGamemodeMessage = othergamemode;
        AdminTools.getInstance().GiveawayCounter = giveawaycount;
        AdminTools.getInstance().GiveawayNotEnough = giveawaynot;
        AdminTools.getInstance().GiveawayStarted = giveawaystart;
        AdminTools.getInstance().GodmodeMessage = godmode;
        AdminTools.getInstance().OtherGodmodeMessage = othergodmode;
        AdminTools.getInstance().NoLongerGodmodeOther = noLongerOthergodmode;
        AdminTools.getInstance().NoGodmodeMessage = noLongerGodmode;
        AdminTools.getInstance().HealMessage = heal;
        AdminTools.getInstance().OtherHealMessage = otherheal;
        AdminTools.getInstance().AllHealMessage = allheal;
        AdminTools.getInstance().AllFeedMessage = allfeed;
        AdminTools.getInstance().AllKicked = allkicked;
        AdminTools.getInstance().LockchatMessage = lockchat;
        AdminTools.getInstance().UnlockchatMessage = unlockchat;
        AdminTools.getInstance().LockchatDenyMessage = lockchatdeny;
        AdminTools.getInstance().AlreadyMuted = alreadyMuted;
        AdminTools.getInstance().StaffMuteMessage = staffMute;
        AdminTools.getInstance().PingLightgreen = pingLightgreen;
        AdminTools.getInstance().PingDarkgreen = pingDarkgreen;
        AdminTools.getInstance().PingLightred = pingLightred;
        AdminTools.getInstance().RenameMessage = rename;
        AdminTools.getInstance().RenameValidItemMessage = renamevalid;
        AdminTools.getInstance().RenameColorWarning = renamecolorwarning;
        AdminTools.getInstance().SignMessage = sign;
        AdminTools.getInstance().SignValidItemMessage = signvalid;
        AdminTools.getInstance().SignColorWarning = signcolorwarning;
        AdminTools.getInstance().SkullName = skullname;
        AdminTools.getInstance().SkullMessage = skullmessage;
        AdminTools.getInstance().OtherSkullMessage = otherskullmessage;
        AdminTools.getInstance().SocialSpyMessage = socialspy;
        AdminTools.getInstance().OtherSocialSpyMessage = othersocialspy;
        AdminTools.getInstance().DisableSocialSpyMessage = disablesocialspy;
        AdminTools.getInstance().OtherDisableSocialSpyMessage = otherdisablesocialspy;
        AdminTools.getInstance().SpeedMessage = speed;
        AdminTools.getInstance().OtherSpeedMessage = otherspeed;
        AdminTools.getInstance().SpeedValidMessage = speedvalid;
        AdminTools.getInstance().PTimeMessage = time;
        AdminTools.getInstance().TpaSenderMessage = tpasender;
        AdminTools.getInstance().TpaIncommingMessage = tpaincomming;
        AdminTools.getInstance().TpallMessage = tpall;
        AdminTools.getInstance().OtherTpallMessage = othertpall;
        AdminTools.getInstance().TpdenyMessage = tpdeny;
        AdminTools.getInstance().OtherTpdenyMessage = othertpdeny;
        AdminTools.getInstance().TpacceptMessage = tpaccept;
        AdminTools.getInstance().OtherTpacceptMessage = othertpaccept;
        AdminTools.getInstance().TphereMessage = tphere;
        AdminTools.getInstance().OtherTphereMessage = othertphere;
        AdminTools.getInstance().UnbanMessage = unban;
        AdminTools.getInstance().IsNotBannedMessage = isnotbanned;
        AdminTools.getInstance().IsNotMutedMessage = isnotmuted;
        AdminTools.getInstance().UnmuteMessage = unmute;
        AdminTools.getInstance().VanishMessage = vanish;
        AdminTools.getInstance().NoLongerVanishMessage = novanish;
        AdminTools.getInstance().OtherVanish = othervanish;
        AdminTools.getInstance().OtherNoLongerVanish = othernovanish;
        AdminTools.getInstance().PWeatherMessage = weather;
        AdminTools.getInstance().OtherWorkbenchMessage = otherworkbench;
        AdminTools.getInstance().WorkbenchMessage = workbench;
        AdminTools.getInstance().Antiban = antiban;
        AdminTools.getInstance().Antimute = antimute;
        AdminTools.getInstance().Modt = modt;
        AdminTools.getInstance().ModtLine1 = modtline1;
        AdminTools.getInstance().ModtLine2 = modtline2;
        AdminTools.getInstance().MaxPlayers = maxplayers;
        AdminTools.getInstance().UnknownCommandBoolean = unknown;
        AdminTools.getInstance().UnknownCommand = unknowncommand;
        AdminTools.getInstance().PublicTime = publictime;
        AdminTools.getInstance().LogIP = logip;
        AdminTools.getInstance().MsgReplyError = msgerror;
        AdminTools.getInstance().AdminchatMessage = adminchat;
        AdminTools.getInstance().DisableUpdateMessage = updatemessage;
        AdminTools.getInstance().AdminchatLogIn = adminchatlogin;
        AdminTools.getInstance().AdminchatLogOff = adminchatlogoff;
        AdminTools.getInstance().AdminchatAlreadyLogOff = adminchatalreadylogoff;
        AdminTools.getInstance().AdminchatAlreadyLogIn = adminchatalreadylogon;
        AdminTools.getInstance().HatMessage = hatCommandMessage;
        AdminTools.getInstance().OtherHatMessage = otherHatCommandMessage;
        AdminTools.getInstance().NoLongerHatMessage = noLongerHatCommandMessage;
        AdminTools.getInstance().OtherNoLongerHatMessage = otherNoLongerHatCommandMessage;
        AdminTools.getInstance().HatErrorMessage = errorHatMessage;
        AdminTools.getInstance().toggleMsgMessage = toggleMsgMessage;
        AdminTools.getInstance().otherToggleMsgMessage = otherToggleMsgMessage;
        AdminTools.getInstance().noMsgMessage = noMsgMessage;
        AdminTools.getInstance().Banned = banned;
        AdminTools.getInstance().MySQLcon = mysql;
    }
    public static void setMySQL()
    {
        FileConfiguration cfg = getMySQLConfig();
        cfg.options().copyDefaults(true);
        cfg.addDefault("username", "root");
        cfg.addDefault("password", "password");
        cfg.addDefault("database", "localhost");
        cfg.addDefault("host", "localhost");
        cfg.addDefault("port", "3306");

        try
        {
            cfg.save(getMySQL());
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }
    public static void readMySQL()
    {
        FileConfiguration cfg = getMySQLConfig();
        MySQL.username = cfg.getString("username");
        MySQL.password = cfg.getString("password");
        MySQL.database = cfg.getString("database");
        MySQL.host = cfg.getString("host");
        MySQL.port = cfg.getString("port");
    }

}
